source 'http://gems.rubyforge.org'
gem 'sinatra', :require => 'sinatra/base'
gem 'json'
gem 'thin'
gem 'shotgun'
gem 'typhoeus'
gem 'yajl-ruby', :require => 'yajl'
gem 'dm-core'
gem 'dm-timestamps'
gem 'dm-migrations'
#gem 'dm-aggregates'
gem 'dm-sqlite-adapter'
#gem 'dm-types'